
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmwehsvidoydigbtzftc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5td2Voc3ZpZG95ZGlnYnR6ZnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODczNTEsImV4cCI6MjA2NTg2MzM1MX0.5V6Kwl--C88l1XIdLypLBV5XkevOmVNwf4ivYWbMsdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
